### ISSUE TITLE
infinity objects needed

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-math#3]
We need a `positive-infinity` (1.0 / 0.0) and `negative-infinity` (-1.0 / 0.0) EO objects here.

Is it possible to implement it?

**Comment by maxonfjvipon** [comment]
@Graur I think it's possible, I'll check what IEEE suggest about it. Also I think we need to change `div` method inside `float` object. Something like this:
```
[] > float
....
[x] > div
  if. > @
    x.eq 0.0
      if.
        ^.eq 1.0
        positive-infinity
        if.
          ^.eq -1.0
         negative-infinity
         []
            "Division by zero exception" > msg
    if.
      eq.
        x.as-bytes
        nan.as-bytes
      nan
      ^.mul (x.pow -1.0)
```

**Comment by maxonfjvipon** [comment]
@Graur Please check this `positive-infinity` object and let me know what you think about it.  
Also I have a question and I have not found an answer yet: should infinities have math operations like `add`, `sub`, `mul`, etc?

**Comment by Graur** [comment]
@maxonfjvipon Could you submit a pull request from branch `#3_infinities` to `main`? It would be easy to check and to view your changes.

> Also I have a question and I have not found an answer yet: should infinities have math operations like add, sub, mul, etc?

Good point, I think they should.
About tricky situations:
`∞ + ∞ = ∞` - compound(+∞, n) is +∞ for n>0 ([IEEE 754: 9.2.1](https://sci-hub.se/10.1109/IEEESTD.2019.8766229))
`∞ * ∞ = ∞` - I guess it will be `1.0/0.0 * 1.0/0.0`, so you are right about it
`∞ ^ ∞ = ∞` -  I think it should works only for `positive-infinity.as-bytes`
`∞ - ∞ = ∞` -  check this [IEEE 754: 7.2 Invalid operation ](https://sci-hub.se/10.1109/IEEESTD.2019.8766229))
`∞ / ∞` -  I guess it will be `1.0/0.0 / 1.0/0.0`, so it would be equal to NaN

Could you double check these links?

**Comment by maxonfjvipon** [comment]
@Graur PR was submitted #4

**Comment by Graur** [comment]
@maxonfjvipon Thanks! Looks great

**Comment by maxonfjvipon** [comment]
@Graur @yegor256 Hey there. I know it's not really related to this issue but look at this: I started to learn IEEE to know how to deal with all these infinities and nan and so on. And it seems there are so many identical and/or unique situations that we should take care of in many places(objects). 

For now we have 5 objects that may have math operations: float, int, nan (we have one for now, IEEE suggest to have two: signaling NaN and quite NaN), positive-infinity, negative-infinity. For each of these objects almost all math operations are valid, but there are cases where exceptions are thrown, like `0.div 0`, `0.mul positive-infinity` and some else. And it seems that in each of these 5 objects we should check the type of the argument (because every operation with `nan` should return `nan`, some operations with infinity are valid, some aren't, we also have negative-infinity and mb we'll have more such specific objects).  

Mb we should make some operations objects? Like:
```
[x, y] > add
# return what we need depends on types of x and y or throw an exception
########
[x, y] > sub
  add x (y.neg) # or x.add (y.neg)
#######
[] > float
   [x] > add
     add ^ x > @
   [x] > sub
     sub ^ x > @
#######
```

In this case we could place all our type verifications in one place. We also can keep `add`, `sub`, etc methods inside `float`, `int`, ... and they will return what these operations objects returns.

Let me know what you think about it.

**Comment by Graur** [comment]
@maxonfjvipon What would type checking inside `add x y` look like then? How can I understand that I've got `int` as `x` or `y`, not `float` in you operation object?
Maybe we should split `int` and `float` objects and decorate them as `rich-int` and `rich-float` with a lot of math operations of each type, instead?

**Comment by yegor256** [comment]
@maxonfjvipon by the way, [the paper](https://github.com/objectionary/on-the-origin-of-objects) doesn't say anything about `nan` object... but it should. Feel free to submit a pull request.

**Comment by Graur** [comment]
@maxonfjvipon Looks great! I absolutely agree with your infinity operations implementation.
