### ISSUE TITLE
arccos object

### ISSUE THREAD

**Issue by includealex** [objectionary/eo-math#73]
I think that we should have an opportunity to count arccos of some value. It can help in implementation Chebyshev Polynomials. For instance, we will have an ability to count them like
$$T_n(x) = \cos {(n \cdot \arccos{(x)})}$$
@Graur what do you think? Do we need object `acos` in `eo-math` or it would be better to avoid having it?

**Comment by Graur** [comment]
@includealex Sounds good to me. But why you choose the name `acos` instead of `arccos`? And if we implement this object, it should be a part of `angle` object.
@maxonfjvipon What do you think?

**Comment by maxonfjvipon** [comment]
@Graur @includealex I like `arccos` too, but I'm not sure if it should belong to `angle` object. 

When we say `(angle 30).cos` we mean that we want to find cosine of the 30 degrees angle, but if we say `(angle 30).arrcos` - it would be kind of wrong, because 30 here is not an 30 degrees angle. 30 is the result of `(angle x).cos` where `x` is the angle we want to find. 

I hope we understood what I meant

**Comment by levBagryansky** [comment]
@includealex maybe arccos should return `angle`?

**Comment by includealex** [comment]
@maxonfjvipon I agree with you

**Comment by maxonfjvipon** [comment]
@levBagryansky maybe, and if user want to work with the result if `arccos` like with just a number, he may call `as-radians` or `as-degrees`
